workflows:
  version: 2
  node-ios:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - ios:
          type: approval
          requires:
            - build
